name: release

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

#on:
#  workflow_dispatch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Publish latest release
        run: sbt publish
