name: test

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  REDOX_API_KEY: ${{ secrets.REDOX_API_KEY }}
  REDOX_API_SECRET: ${{ secrets.REDOX_API_SECRET }}

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master, dboreham/scala-2-13 ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Run tests
        run: sbt test
